version: "3.7"

services:
  api:
    container_name: motors_shop_back
    image: node:16-alpine
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PWD
      - POSTGRES_DB=POSTGRES_DB