version: "3.7"

services:
    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=motors_shop_db
            - POSTGRES_HOST=POSTGRES_HOST
        volumes:
            - pgdata:/data/postgres
        ports:
            - "5433:5432"

    api:
        container_name: motors_shop
        build: .
        volumes:
            - .:/app
        depends_on:
            - db
        ports:
            - "3000:3000"
volumes:
    pgdata:
        driver: local